### ISSUE TITLE
Suggestions for a better footer

### ISSUE THREAD

**Issue by DPDmancul** [electricant/beamerThemePadovaDEI#1]
I have an issue (1) and some suggestions (2, 3 and 4) for a better footer:

1. use `\insertshortauthor` instead of `\insertauthor` in https://github.com/electricant/beamerThemePadovaDEI/blob/056fdfffbddbc859119aab0ecc62cd05654776c2/beamerouterthemePadovaDEI.sty#L79  
in this way users can set an optional shortauthor text in title definition (see [Beamer guide](http://ctan.mirror.garr.it/mirrors/CTAN/macros/latex/contrib/beamer/doc/beameruserguide.pdf), page 65).
2. use `/` instead of `of` for better internationalization in https://github.com/electricant/beamerThemePadovaDEI/blob/056fdfffbddbc859119aab0ecc62cd05654776c2/beamerouterthemePadovaDEI.sty#L75
3. Add the title: 
```
\pgftext[top,at=\pgfpoint{0.5\paperwidth}{0.025\paperwidth}]{
    \usebeamerfont{frame number in foot}
    \usebeamercolor[fg]{frame number in foot}\insertshorttitle 
  }
```
4. Adjust the footer text alignment: in 4:3 `0.025\paperwidth` is correct, but in 16:9 it will be better `0.020\paperwidth`.

**Comment by electricant** [comment]
Great ideas! Thank you. I'm looking forward to add them to the code. Why don't you submit a pull request so that I can merge your suggestions?

**Comment by electricant** [comment]
Pull request merged. Closing. Thanks again.
