### ISSUE TITLE
Publishing on CTAN

### ISSUE THREAD

**Issue by DPDmancul** [electricant/beamerThemePadovaDEI#4]
I think it could be very helpful to publish this package on CTAN (eg. `/macros/latex/contrib/beamer-contrib/themes/padova/beamertheme-padovadei`) in order to allow build presentations with TexLive as only dependence (as for example on Overleaf). I asked the CTAN team and they have found the following problems: 

1. The most important problem is the license: this package has no license and contains two logos which I think are under copyright. To give the package a license is easy, but I don't know how to deal with copyrighted logos.
2. The package has no version: a version must be clearly stated. Also other metadata (e.g. author names, license, ...) must be stated in the package.

Then they suggest other minor changes:

> -> Please pay attention that [README.md](http://readme.md/) should contain the
> information requested in item a. of
> https://mirrors.ctan.org/help/ctan/CTAN-upload-addendum.html#readme
> This will also resolve some of the issues mentioned above.
> 
> -> It would do no harm if the essential administrative data
> were also mentioned in comments at the top of the .sty
> files.
> 
> -> I would suggest giving sample_presentation.{tex|pdf} a name
> that is more specific to your particular beamer theme.

**Comment by DPDmancul** [comment]
This package for example https://www.ctan.org/tex-archive/graphics/coloremoji is released under Latex Project Public License and includes Apple Color Emoji which are copyrighted.

**Comment by electricant** [comment]
Hi and thanks for your input.

Adding a README file and a license is the easy part.

For the logos I'll double check with the university marketing department ad report back.

**Comment by electricant** [comment]
Since this issue involves many subtasks I created the following projects to keep track of them.
https://github.com/electricant/beamerThemePadovaDEI/projects/1

Feel free to fork this repo if you'd like to help with some of those issues.

**Comment by electricant** [comment]
As explained in the pull request the university does not allow the usage of its logos outside official communication material.

> è vietato l'uso del sigillo di Ateneo in materiali autoprodotti a meno che non siano materiali promozionali di eventi espressamente autorizzati (veda regolamento qui https://www.unipd.it/patrocini-uso-sigillo).
> 
> Per presentazioni scientifiche può usare i modelli ufficiali che trova nella sezione del sito accessibile con Single Sign On.

Sadly, we cannot go ahead and add this theme on CTAN.
